# Site Settings
title: Ting-Yu Kuo Resume 
url: 'https://sealpuppy.github.io/'
baseurl: '/Online_CV_HR' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Ting-Yu (Terry) Kuo 
tagline: 
pic: profilepic.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: '3 years experience working as a personnel consultant in the software domain with result-oriented working style. Skilled in long-term productive relationship building, strategic sourcing, and recruitment pipeline management. Always willing to listen, learn, and share.
'

#sidebar links
email: oldiegoodie99@gmail.com
phone: +886 933 605 616
linkedin: terry-kuo-
github: sealpuppy
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
